name: Format, Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Format Code
        run: cargo fmt -- --check

  build:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Project
        run: cargo build --release

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Bump Version and Release
        run: |
          # Bump the version
          cargo install cargo-release
          cargo release patch --no-publish
          # Push tags
          git push --follow-tags
